name: compile
on: [ push, pull_request ]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: sudo apt-get install libyaml-dev
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml git+https://github.com/TwitchPlaysPokemon/pokecat.git
      - name: compile pokesets
        run: python compile.py
      - uses: actions/upload-artifact@v2
        with:
          name: pbrpokemondb.json
          path: pbrpokemondb.json
